[package]
name = "ow_2_multi"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.9.0"
gdk = "0.9.0"
glade = "0.9.0"
rand = "0.8.5"
log = "0.4.14"
simple_logger = "1.11.0"

[profile.release]
opt-level = 3